### ISSUE TITLE
Sejong is never going to build timestamps

### ISSUE THREAD

**Issue by shinyfoil** [geometry-labs/icon-blocks#117]
Sejong's block 1 has a timestamp of 0:

```
{
    "jsonrpc": "2.0",
    "result": {
        "block_hash": "60f2b7d39f7e07ddbec7f8a5966d992d6db53b5f8a2fc2a21dc498b872c06bcf",
        "confirmed_transaction_list": [],
        "height": 1,
        "merkle_tree_root_hash": "",
        "peer_id": "hxd317634efef2c9a08638ce1702335020af82619a",
        "prev_block_hash": "61497566ec3a1459685dc96ea763ffae76edd150b3f1cb537418f8fe12aa0acc",
        "signature": "",
        "time_stamp": 0,
        "version": "2.0"
    },
    "id": 1234
}
```

If we're checking that no block has a timestamp of 0 (https://github.com/geometry-labs/icon-blocks/blob/main/src/worker/builders/block_time_builder.go#L38), we're never going to be able to process any timestamps. Should we be putting in a network flag or something goofy to override this behaviour? Or maybe just a special case for block 1? We could also probably just fudge it and set timestamp for block 1 to 1.

**Comment by pranav925** [comment]
Could this be solved by having the ETL manually setting block #1's timestamp to block #2's timestamp, or just 1?

**Comment by shinyfoil** [comment]
I mean, I'll always advocate against having special custom logic that changes data in ETL. The purpose of ETL is to dump the data as faithfully as it can. We could always just go into the DB and adjust it ourselves, but there's also no guarantee the next testnet is going to have a 0 timestamp for block 1.
