### ISSUE TITLE
Block 1,753,354 missing in prod-us blocks service

### ISSUE THREAD

**Issue by pranav925** [geometry-labs/icon-blocks#118]
Use the `CONSUMER_IS_PARTITION_CONSUMER` feature flag to fill in block

**Comment by pranav925** [comment]
https://tracker.icon.community/block/1753354

**Comment by shinyfoil** [comment]
I think I got this now? It's at least got a timestamp now: https://usw2.tracker.icon.geometry.io/block/1753354
