### ISSUE TITLE
Add CodeCov 

### ISSUE THREAD

**Issue by pranav925** [geometry-labs/icon-blocks#26]

**Comment by robcxyz** [comment]
I am not seeing the flags come up in codecov and don't know if the integration tests are being uploaded. Can @pranav925 verify that we are getting that coverage?  

[The CI pipeline that is uploading the coverage is does have the `flags` field set.](https://github.com/geometry-labs/icon-blocks/actions/runs/1061531179/workflow#L34)

There are changes to the coverage but those are related to unit tests.  The API still doesn't have coverage it seems which should have happened from the integration tests. Perhaps this needs to be run manually to validate that the coverage report is being generated properly for int tests.

**Comment by pranav925** [comment]
The Integration tests are in a different folder with a different go.mod, so it should not be counted on that command. 

Integration tests are fired here: https://github.com/geometry-labs/icon-blocks/actions/runs/1061531179/workflow#L43
