### ISSUE TITLE
Return x-total-count header 

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-blocks#32]
Need to return the x-total-count header as the max records in the set.  This informs page size and in many cases, total records such as blocks, total Txs, etc. Will have it in every get.

**Comment by pranav925** [comment]
https://stackoverflow.com/questions/3715981/what-s-the-best-restful-method-to-return-total-number-of-items-in-an-object

**Comment by pranav925** [comment]
Added this header to blocks, transactions, and logs
