### ISSUE TITLE
primary vs secondary db connection

### ISSUE THREAD

**Issue by shinyfoil** [geometry-labs/icon-blocks#66]
the pg cluster has three nodes: 1 master, 2 replicas. the replicas are exposed separately from the master, however, replication might be delayed. how much replication delay can we tolerate? can we connect the worker to the master and the api to the replicas so that we can scale better?

**Comment by pranav925** [comment]
The icon block time is 2 seconds, the delay needs to be less than that in order for the replicas to catch up.

Sub 1 second will be ideal if we separate the API and worker db connections
